# Generated by Django 4.2.6 on 2023-11-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TheatreShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='public/theatreimages')),
                ('genre', models.CharField(max_length=100)),
                ('typescene', models.CharField(choices=[('Основна сцена', 'Основна сцена'), ('Камерна сцена', 'Камерна сцена')], default='Основна сцена', max_length=150)),
                ('num_scene', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('formatted_date', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatrehome.row')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatrehome.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatrehome.theatreshow')),
            ],
        ),
    ]
