# Generated by Django 4.2.6 on 2023-11-26 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatrehome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatreshow',
            name='time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='theatreshow',
            name='date',
            field=models.DateField(),
        ),
    ]
