# Generated by Django 4.2.6 on 2023-12-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatrehome', '0003_remove_bookedseats_name_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedseats',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookedseats',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='bookedseats',
            name='surname',
        ),
    ]
